export const API_KEY = "a35eb9b2a0da4da2cd02766b7d42ed24";
export const IMAGE_URL = "https://image.tmdb.org/t/p/w500";
export const movieId = new URLSearchParams(window.location.search).get("id");
export const MOVIE_API_URL = `https://api.themoviedb.org/3/movie/${movieId}?api_key=${API_KEY}&language=es-ES`;
export const CAST_API_URL = `https://api.themoviedb.org/3/movie/${movieId}/credits?api_key=${API_KEY}&language=es-ES`;
export const TV_CAST_API_URL = `https://api.themoviedb.org/3/tv/${movieId}/credits?api_key=${API_KEY}&language=es-ES`;
export const YOUTUBE_API_KEY = "AIzaSyBa4JfbgovmH0oBE3jHBJSfqTxlBCP0sZM";
export const REVIEWS_API_URL = `https://api.themoviedb.org/3/movie/${movieId}/reviews?api_key=${API_KEY}&language=es-ES`;
export const ACTOR_API_URL = `https://api.themoviedb.org/3/person/${movieId}?api_key=${API_KEY}&language=es-ES`;
export const ACTOR_MOVIE_CREDITS_API_URL = `https://api.themoviedb.org/3/person/${movieId}/movie_credits?api_key=${API_KEY}&language=es-ES`;
export const ACTOR_TV_CREDITS_API_URL = `https://api.themoviedb.org/3/person/${movieId}/tv_credits?api_key=${API_KEY}&language=es-ES`;
export const GENRE_API_URL = `https://api.themoviedb.org/3/discover/movie?api_key=${API_KEY}&with_genres=${movieId}`;
export const SEARCH_API_URL = `https://api.themoviedb.org/3/search/movie?api_key=${API_KEY}&query=`;
export const SEARCH_ALL = `https://api.themoviedb.org/3/search/multi?language=es-ES&api_key=${API_KEY}&query=`;
export const serieId = new URLSearchParams(window.location.search).get("id");
export const SERIE_API_URL = `https://api.themoviedb.org/3/tv/${serieId}?api_key=${API_KEY}&language=es-ES`;
export const SERIE_CAST_API_URL = `https://api.themoviedb.org/3/tv/${serieId}/credits?api_key=${API_KEY}&language=es-ES`;
export const GENRE_SERIES_API_URL_ = `https://api.themoviedb.org/3/discover/tv?api_key=${API_KEY}&with_genres=${movieId}`;
export const TV_REVIEW_API_URL = `https://api.themoviedb.org/3/tv/${serieId}/reviews?api_key=${API_KEY}&language=en-`;
