site_name: Film-E Docs
site_description: Documentación de Film-E
site_author: Juan Manuel y Miguel Ángel
repo_url: https://github.com/Juanma0186/Film-E
repo_name: Proyecto Film-E

theme:
  name: material
  language: es
  palette: 
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: Copyright &copy; 2023

nav:
  - Inicio: index.md
  - Primeros pasos:
    - Vite: vite.md
    - Tailwind: tailwind.md
    - API: api.md
  - Diseño: 
      - Excalidraw: excalidraw.md  
      - Principal: paginaPrincipal.md  
      - Detalles: paginaDetalles.md
  - Buscadores: 
      - Ajax: buscadorAjax.md
      - BuscadorPeli: buscadorPeli.md
      - ApiYoutube: apiYoutube.md
